// ============================================================
//  LOCATION MASTER DATA — single source of truth
//  Mirrored in admin/src/lib/locationData.ts — edit BOTH files
//  if the data ever changes so ad targeting stays accurate.
// ============================================================

export const STATES: string[] = [
  'Gujarat',
  'Rajasthan',
  'Maharashtra',
  'Madhya Pradesh',
  'Uttar Pradesh',
  'Delhi',
  'Karnataka',
  'Tamil Nadu',
  'Andhra Pradesh',
  'Telangana',
  'Kerala',
  'Bihar',
  'West Bengal',
  'Odisha',
  'Assam',
  'Punjab',
  'Haryana',
  'Himachal Pradesh',
  'Uttarakhand',
  'Jharkhand',
  'Chhattisgarh',
  'Goa',
  'Jammu & Kashmir',
  'Other',
]

// All 33 Gujarat districts (alphabetical); other states have a minimal list.
export const DISTRICTS_BY_STATE: Record<string, string[]> = {
  Gujarat: [
    'Ahmedabad',
    'Amreli',
    'Anand',
    'Aravalli',
    'Banaskantha',
    'Bharuch',
    'Bhavnagar',
    'Botad',
    'Chhota Udaipur',
    'Dahod',
    'Dang',
    'Devbhumi Dwarka',
    'Gandhinagar',
    'Gir Somnath',
    'Jamnagar',
    'Junagadh',
    'Kheda',
    'Kutch',
    'Mahisagar',
    'Mehsana',
    'Morbi',
    'Narmada',
    'Navsari',
    'Panchmahal',
    'Patan',
    'Porbandar',
    'Rajkot',
    'Sabarkantha',
    'Surat',
    'Surendranagar',
    'Tapi',
    'Vadodara',
    'Valsad',
  ],
  Rajasthan:        ['Jaipur', 'Jodhpur', 'Udaipur', 'Ajmer', 'Kota', 'Bikaner', 'Other'],
  Maharashtra:      ['Pune', 'Mumbai', 'Nashik', 'Nagpur', 'Aurangabad', 'Kolhapur', 'Other'],
  'Madhya Pradesh': ['Bhopal', 'Indore', 'Gwalior', 'Jabalpur', 'Other'],
  'Uttar Pradesh':  ['Lucknow', 'Varanasi', 'Agra', 'Kanpur', 'Prayagraj', 'Other'],
  Delhi:            ['Central Delhi', 'East Delhi', 'North Delhi', 'South Delhi', 'West Delhi', 'Other'],
  Karnataka:        ['Bengaluru Urban', 'Mysuru', 'Mangaluru', 'Hubli-Dharwad', 'Other'],
  'Tamil Nadu':     ['Chennai', 'Coimbatore', 'Madurai', 'Salem', 'Other'],
  'Andhra Pradesh': ['Visakhapatnam', 'Vijayawada', 'Guntur', 'Tirupati', 'Other'],
  Telangana:        ['Hyderabad', 'Warangal', 'Karimnagar', 'Nizamabad', 'Other'],
  Kerala:           ['Thiruvananthapuram', 'Kochi', 'Kozhikode', 'Thrissur', 'Other'],
  Bihar:            ['Patna', 'Gaya', 'Bhagalpur', 'Muzaffarpur', 'Other'],
  'West Bengal':    ['Kolkata', 'Howrah', 'Durgapur', 'Asansol', 'Other'],
  Odisha:           ['Bhubaneswar', 'Cuttack', 'Rourkela', 'Other'],
  Assam:            ['Guwahati', 'Dibrugarh', 'Silchar', 'Other'],
  Punjab:           ['Ludhiana', 'Amritsar', 'Jalandhar', 'Patiala', 'Other'],
  Haryana:          ['Gurugram', 'Faridabad', 'Rohtak', 'Panipat', 'Other'],
  'Himachal Pradesh': ['Shimla', 'Manali', 'Dharamshala', 'Other'],
  Uttarakhand:      ['Dehradun', 'Haridwar', 'Nainital', 'Other'],
  Jharkhand:        ['Ranchi', 'Jamshedpur', 'Dhanbad', 'Other'],
  Chhattisgarh:     ['Raipur', 'Bhilai', 'Bilaspur', 'Other'],
  Goa:              ['North Goa', 'South Goa'],
  'Jammu & Kashmir': ['Jammu', 'Srinagar', 'Anantnag', 'Other'],
  Other:            ['Other'],
}

// Major towns / talukas per Gujarat district (used for city picker)
export const CITIES_BY_DISTRICT: Record<string, string[]> = {
  Ahmedabad:         ['Ahmedabad City', 'Bavla', 'Dhandhuka', 'Dholka', 'Mandal', 'Sanand', 'Viramgam'],
  Amreli:            ['Amreli', 'Babra', 'Bagasara', 'Dhola', 'Jafrabad', 'Khambha', 'Lathi', 'Rajula', 'Savarkundla'],
  Anand:             ['Anand', 'Borsad', 'Khambhat', 'Petlad', 'Sojitra', 'Umreth', 'Vallabh Vidyanagar'],
  Aravalli:          ['Bayad', 'Bhiloda', 'Dhansura', 'Malpur', 'Meghraj', 'Modasa'],
  Banaskantha:       ['Amirgadh', 'Bhabhar', 'Danta', 'Dantiwada', 'Deesa', 'Deodar', 'Kankrej', 'Palanpur', 'Tharad', 'Vadgam', 'Vav'],
  Bharuch:           ['Amod', 'Ankleshwar', 'Bharuch', 'Hansot', 'Jambusar', 'Jhagadia', 'Netrang', 'Vagra', 'Walia'],
  Bhavnagar:         ['Bhavnagar', 'Gadhada', 'Gariadhar', 'Ghogha', 'Mahuva', 'Palitana', 'Sihor', 'Talaja', 'Umrala', 'Vallabhipur'],
  Botad:             ['Barwala', 'Botad', 'Gadhada', 'Ranpur'],
  'Chhota Udaipur':  ['Bodeli', 'Chhota Udaipur', 'Jetpur Pavi', 'Kavant', 'Nasvadi', 'Sankheda'],
  Dahod:             ['Dahod', 'Devgadh Baria', 'Dhanpur', 'Fatepura', 'Garbada', 'Jhalod', 'Limkheda', 'Sanjeli'],
  Dang:              ['Ahwa', 'Subir', 'Waghai'],
  'Devbhumi Dwarka': ['Bhanvad', 'Dwarka', 'Kalyanpur', 'Khambhalia', 'Okhamandal'],
  Gandhinagar:       ['Dehgam', 'Gandhinagar City', 'Kalol', 'Mansa'],
  'Gir Somnath':     ['Kodinar', 'Sutrapada', 'Talala', 'Una', 'Veraval'],
  Jamnagar:          ['Dhrol', 'Jamnagar City', 'Jodia', 'Kalavad', 'Lalpur'],
  Junagadh:          ['Junagadh City', 'Keshod', 'Manavadar', 'Mangrol', 'Mendarda', 'Vanthali', 'Visavadar'],
  Kheda:             ['Balasinor', 'Kapadvanj', 'Kathlal', 'Kheda', 'Mahudha', 'Matar', 'Mehmedabad', 'Nadiad', 'Thasra'],
  Kutch:             ['Abdasa', 'Anjar', 'Bhachau', 'Bhuj', 'Gandhidham', 'Lakhpat', 'Mandvi', 'Mundra', 'Nakhatrana', 'Rapar'],
  Mahisagar:         ['Balasinor', 'Khanpur', 'Lunawada', 'Santrampur', 'Virpur'],
  Mehsana:           ['Becharaji', 'Kadi', 'Kheralu', 'Mehsana City', 'Satlasana', 'Sidhpur', 'Unjha', 'Vadnagar', 'Vijapur', 'Visnagar'],
  Morbi:             ['Halvad', 'Maliya Miyana', 'Morbi City', 'Tankara', 'Wankaner'],
  Narmada:           ['Dediapada', 'Garudeshwar', 'Nandod', 'Sagbara', 'Tilakwada'],
  Navsari:           ['Chikhli', 'Gandevi', 'Jalalpore', 'Navsari City', 'Vansda'],
  Panchmahal:        ['Godhra', 'Ghoghamba', 'Halol', 'Kalol', 'Morva Hadaf', 'Shehera'],
  Patan:             ['Chanasma', 'Harij', 'Patan City', 'Radhanpur', 'Sami', 'Santalpur', 'Sidhpur'],
  Porbandar:         ['Kutiyana', 'Porbandar City', 'Ranavav'],
  Rajkot:            ['Dhoraji', 'Gondal', 'Jasdan', 'Jetpur', 'Kotda Sangani', 'Lodhika', 'Paddhari', 'Rajkot City', 'Upleta', 'Vinchhiya'],
  Sabarkantha:       ['Bayad', 'Dhansura', 'Himatnagar', 'Idar', 'Khedbrahma', 'Modasa', 'Prantij', 'Talod', 'Vadali', 'Vijaynagar'],
  Surat:             ['Bardoli', 'Kamrej', 'Mandvi', 'Mangrol', 'Olpad', 'Palsana', 'Surat City', 'Umarpada'],
  Surendranagar:     ['Chotila', 'Dhrangadhra', 'Halvad', 'Lakhtar', 'Limbdi', 'Muli', 'Patdi', 'Sayla', 'Surendranagar City', 'Thangadh', 'Wadhwan'],
  Tapi:              ['Dolvan', 'Nizar', 'Songadh', 'Uchchhal', 'Valod', 'Vyara'],
  Vadodara:          ['Dabhoi', 'Desar', 'Karjan', 'Padra', 'Savli', 'Sinor', 'Vadodara City', 'Waghodia'],
  Valsad:            ['Dharampur', 'Kaprada', 'Pardi', 'Umbergaon', 'Valsad City', 'Vapi'],
}

// Region → set of districts (for tier-3 "nearby district" matching).
// Admins set `region` on an ad; the API derives the student's region from
// their district using REGION_BY_DISTRICT and compares the two strings.
export const REGIONS: string[] = [
  'North Gujarat',
  'Central Gujarat',
  'South Gujarat',
  'Saurashtra',
  'Kutch',
]

export const REGION_BY_DISTRICT: Record<string, string> = {
  // North Gujarat
  Banaskantha:       'North Gujarat',
  Mehsana:           'North Gujarat',
  Patan:             'North Gujarat',
  Sabarkantha:       'North Gujarat',
  Aravalli:          'North Gujarat',
  Gandhinagar:       'North Gujarat',
  // Central Gujarat
  Ahmedabad:         'Central Gujarat',
  Anand:             'Central Gujarat',
  Kheda:             'Central Gujarat',
  Mahisagar:         'Central Gujarat',
  Panchmahal:        'Central Gujarat',
  Vadodara:          'Central Gujarat',
  'Chhota Udaipur':  'Central Gujarat',
  Dahod:             'Central Gujarat',
  // South Gujarat
  Surat:             'South Gujarat',
  Bharuch:           'South Gujarat',
  Narmada:           'South Gujarat',
  Navsari:           'South Gujarat',
  Tapi:              'South Gujarat',
  Valsad:            'South Gujarat',
  Dang:              'South Gujarat',
  // Saurashtra
  Amreli:            'Saurashtra',
  Bhavnagar:         'Saurashtra',
  Botad:             'Saurashtra',
  'Devbhumi Dwarka': 'Saurashtra',
  'Gir Somnath':     'Saurashtra',
  Jamnagar:          'Saurashtra',
  Junagadh:          'Saurashtra',
  Morbi:             'Saurashtra',
  Porbandar:         'Saurashtra',
  Rajkot:            'Saurashtra',
  Surendranagar:     'Saurashtra',
  // Kutch
  Kutch:             'Kutch',
}
